baseURL = 'https://aaronkredshaw.com'
languageCode = 'en-us'
title = "HOW TO GET A JOB IN TECHNICAL WRITING"
theme = "paper"
[params]
 color = 'linen'
  subtitle = 'How to get a job in technical writing'
  favicon="/img/favicon-32-32.png"
  enableLightDarkTheme = true
  [params.contact]
    email = 'akredshaw@gmail.com'
