baseURL = 'https://aaronkredshaw.com/'
languageCode = 'en-us'
title = "Aaron K. Redshaw"
theme = "hugo-theme-cleanwhite"
[params]
  subtitle = 'How to get a job in technical writing'
  favicon="/img/favicon-32-32.png"
  enableLightDarkTheme = true
  [params.contact]
    email = 'akredshaw@gmail.com'
