baseURL = 'https://aaronkredshaw.com/'
languageCode = 'en-us'
title = "Aaron Redshaw's Tech Writing Blog"
theme = "lekh"
[params]
  subtitle = 'The Best Widgets on Earth'
  [params.contact]
    email = 'akredshaw@gmail.com'
