baseURL = 'https://aaronkredshaw.com/'
languageCode = 'en-us'
title = "Aaron K. Redshaw"
theme = "bilberry-hugo-theme"
[params]
  subtitle = 'How to get a job in technical writing'
  [params.contact]
    email = 'akredshaw@gmail.com'
